name: CI

on:
  pull_request:
    paths:
      - '**'

  push:
    branches:
      - develop
      - omad-develop
    paths:
      - '**'
      - '!docs/**'
      - '!contrib/**'

  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgis/postgis:16-3.5
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: datacube
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5432:5432
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        persist-credentials: false

    - name: Config
      id: cfg
      run: |
        push_test_pypi=no
        push_pypi=no

        if [[ "${GITHUB_REF}" =~ refs/tags/.* ]]; then
          echo "push_test_pypi=yes" >> $GITHUB_OUTPUT
          echo "push_pypi=yes" >> $GITHUB_OUTPUT
        fi

    - name: Install uv
      uses: astral-sh/setup-uv@v5

    - name: Install package in virtual environment
      run: |
        uv venv --python 3.12.9  # Use a version of python installed by uv
        source .venv/bin/activate
        uv pip install --verbose -e '.[test]'

    - name: Create Postgres tables and datacube testing config
      run: |
        createdb pgintegration
        createdb pgisintegration

        cat <<EOL > $HOME/.datacube_integration.conf
        [datacube]
        db_hostname: localhost
        db_database: pgintegration
        db_username: postgres
        db_password: postgres
        index_driver: default
        
        [postgis]
        db_hostname: localhost
        db_username: postgres
        db_password: postgres
        db_database: pgisintegration
        index_driver: postgis
        
        [nosuchdriverenv]
        db_hostname:
        index_driver: no_such_driver
        
        [nulldriver]
        index_driver: null
        
        [localmemory]
        index_driver: memory
        
        EOL
      env:
        PGHOST: localhost
        PGPORT: 5432
        PGUSER: postgres
        PGPASSWORD: postgres
        PGDATABASE: datacube

    - name: Run Tests
      run: |

        source .venv/bin/activate
        echo "Run tests"
        uv pip install -e ./tests/drivers/fail_drivers --no-deps
        uv pip install -e ./examples/io_plugin --no-deps
        pytest -r a \
          --cov datacube \
          --cov-report=xml \
          --doctest-ignore-import-errors \
          --durations=5 \
          datacube \
          tests \
          integration_tests


    - name: Build Packages
      run: |
        uv build
        ls -lh ./dist/
        twine check ./dist/*

    - name: Publish to Test PyPi
      if: |
        steps.cfg.outputs.push_test_pypi == 'yes'
      run: |
            twine upload \
              --verbose \
              --non-interactive \
              --disable-progress-bar \
              --username=__token__ \
              --password=${TWINE_PASSWORD} \
              --repository-url=${TWINE_REPOSITORY_URL} \
              --skip-existing dist/* || true
      env:
        TWINE_PASSWORD: ${{ secrets.TestPyPiToken }}
        TWINE_REPOSITORY_URL: 'https://test.pypi.org/legacy/'

    - name: Publish to PyPi
      if: |
        github.event_name == 'push'
        && steps.cfg.outputs.push_pypi == 'yes'
      run: |
            twine upload \
              --verbose \
              --non-interactive \
              --disable-progress-bar \
              --username=__token__ \
              --password=${TWINE_PASSWORD} \
              --skip-existing dist/*
      env:
        TWINE_PASSWORD: ${{ secrets.PyPiToken }}

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v5
      with:
        file: ./coverage.xml
        fail_ci_if_error: false
        token: ${{ secrets.CODECOV_TOKEN }}
